# Generated by Django 2.1.5 on 2019-04-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_plot',
            field=models.CharField(max_length=10000),
        ),
    ]
