# Generated by Django 2.1.5 on 2019-04-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_genre', models.CharField(max_length=100)),
                ('movie_plot', models.CharField(max_length=100)),
                ('movie_link', models.CharField(max_length=100)),
                ('imdb_rating', models.CharField(max_length=100)),
            ],
        ),
    ]
