# Generated by Django 2.1.5 on 2019-04-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('movie_id', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Movie_Data',
            new_name='Movie',
        ),
    ]
