# Generated by Django 2.1.5 on 2019-04-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_plot',
            field=models.CharField(max_length=10000),
        ),
    ]
